FROM node:16.13.2

RUN ln -fs /usr/share/zoneinfo/US/Pacific-New /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

WORKDIR /home/node/server

ADD "./package.json" "/home/node/server/package.json"

RUN ["npm", "i", "-g", "pnpm"]

RUN ["npm", "i", "-g", "nodemon"]

RUN ["pnpm", "i", "opencollective-postinstall"]

#npm i --no-bin-links --no-optional

CMD ["pnpm", "run", "windows"]
